apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-team-label-from-namespace
spec:
  rules:
    - name: copy-team-label-from-namespace
      match:
        any:
          - resources:
              kinds:
                - Pod
      context:
        - name: ns
          apiCall:
            urlPath: "/api/v1/namespaces/{{request.namespace}}"
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              team: "{{ ns.metadata.labels.team }}"
